import type { Device } from "@/types/homelab";

const now = new Date().toISOString();

const d = (
  id: string,
  data: Omit<Device, "id" | "createdAt" | "updatedAt">,
): Device => ({ id, createdAt: now, updatedAt: now, ...data });

export const demoDevices: Device[] = [
  d("dev-proxmox", {
    name: "proxmox-01",
    type: "Server",
    status: "Online",
    os: "Proxmox VE 8.2",
    cpu: "AMD Ryzen 9 5900X (12c/24t)",
    ram: 128,
    storage: 4000,
    address: "10.0.0.10 / proxmox-01.lan",
    location: "Basement rack — U3",
    notes: "Main hypervisor. ZFS mirror on NVMe, weekly scrub Sunday 03:00.",
    services: [
      { id: "s1", name: "SSH", status: "Running" },
      { id: "s2", name: "Proxmox Web UI", status: "Running" },
      { id: "s3", name: "ZFS", status: "Running" },
      { id: "s4", name: "Prometheus Exporter", status: "Running" },
    ],
  }),
  d("dev-truenas", {
    name: "truenas-nas",
    type: "NAS",
    status: "Online",
    os: "TrueNAS SCALE 24.04",
    cpu: "Intel Xeon E-2246G",
    ram: 64,
    storage: 48000,
    address: "10.0.0.20 / nas.lan",
    location: "Basement rack — U5",
    notes: "8x6TB RAIDZ2. Snapshots hourly, replication to offsite nightly.",
    services: [
      { id: "s1", name: "SMB", status: "Running" },
      { id: "s2", name: "NFS", status: "Running" },
      { id: "s3", name: "SSH", status: "Running" },
      { id: "s4", name: "Syncthing", status: "Stopped" },
    ],
  }),
  d("dev-media", {
    name: "media-vm",
    type: "VM",
    status: "Online",
    os: "Debian 12",
    cpu: "6 vCPU (passthrough iGPU)",
    ram: 16,
    storage: 500,
    address: "10.0.0.31 / media.lan",
    location: "proxmox-01",
    notes: "Jellyfin hardware transcoding via QSV. Behind Nginx reverse proxy.",
    services: [
      { id: "s1", name: "Jellyfin", status: "Running" },
      { id: "s2", name: "Docker", status: "Running" },
      { id: "s3", name: "Nginx", status: "Running" },
      { id: "s4", name: "qBittorrent", status: "Error" },
    ],
  }),
  d("dev-pihole", {
    name: "pi-hole",
    type: "Raspberry Pi",
    status: "Online",
    os: "Raspberry Pi OS Lite (64-bit)",
    cpu: "Broadcom BCM2711 (4c)",
    ram: 4,
    storage: 64,
    address: "10.0.0.5 / dns.lan",
    location: "Office shelf",
    notes: "Primary DNS + DHCP. Unbound upstream, no external resolvers.",
    services: [
      { id: "s1", name: "Pi-hole", status: "Running" },
      { id: "s2", name: "Unbound", status: "Running" },
      { id: "s3", name: "SSH", status: "Running" },
    ],
  }),
  d("dev-k3s", {
    name: "k3s-node-02",
    type: "Server",
    status: "Maintenance",
    os: "Ubuntu Server 24.04 LTS",
    cpu: "Intel i5-8500T (6c)",
    ram: 32,
    storage: 1000,
    address: "10.0.0.42 / k3s02.lan",
    location: "Basement rack — U7",
    notes: "Kernel upgrade in progress, cordoned & drained.",
    services: [
      { id: "s1", name: "k3s agent", status: "Stopped" },
      { id: "s2", name: "SSH", status: "Running" },
      { id: "s3", name: "containerd", status: "Stopped" },
    ],
  }),
  d("dev-backup", {
    name: "backup-box",
    type: "PC",
    status: "Offline",
    os: "Alpine Linux 3.20",
    cpu: "Intel N100 (4c)",
    ram: 8,
    storage: 8000,
    address: "10.0.0.60 / backup.lan",
    location: "Garage cabinet",
    notes: "Wake-on-LAN nightly at 02:00 for restic backups, then powers off.",
    services: [
      { id: "s1", name: "restic", status: "Stopped" },
      { id: "s2", name: "SSH", status: "Stopped" },
    ],
  }),
  d("dev-thinkpad", {
    name: "thinkpad-t480",
    type: "Laptop",
    status: "Online",
    os: "Arch Linux",
    cpu: "Intel i7-8650U (4c/8t)",
    ram: 32,
    storage: 1000,
    address: "10.0.0.101 / t480.lan",
    location: "Desk",
    notes: "Daily driver. Tailscale exit node when travelling.",
    services: [
      { id: "s1", name: "Tailscale", status: "Running" },
      { id: "s2", name: "Docker", status: "Running" },
    ],
  }),
];
